import type { LucideIcon } from "lucide-react";
import {
  Circle,
  Flame,
  Droplets,
  Zap,
  Leaf,
  Snowflake,
  Swords,
  Skull,
  Mountain,
  Wind,
  Brain,
  Bug,
  Gem,
  Ghost,
  Sparkles,
  Moon,
  Shield,
  Heart,
} from "lucide-react";

export const typeIcons: Record<string, LucideIcon> = {
  normal: Circle,
  fire: Flame,
  water: Droplets,
  electric: Zap,
  grass: Leaf,
  ice: Snowflake,
  fighting: Swords,
  poison: Skull,
  ground: Mountain,
  flying: Wind,
  psychic: Brain,
  bug: Bug,
  rock: Gem,
  ghost: Ghost,
  dragon: Sparkles,
  dark: Moon,
  steel: Shield,
  fairy: Heart,
};
